### ISSUE TITLE
release tag 1.3 does not contain namespace implementation?

### ISSUE THREAD

**Issue by Sega-Zero** [path/FastImageCache#101]
Installed library via cocoapods with `pod 'FastImageCache', '~> 1.3'` in Podfile and haven't found `initWithNamespace` method, but, according to [changelist](https://github.com/path/FastImageCache/compare/1.3...master) it should be there. Checked the zip file attached to release and couldn't find it there too. Should it be there or not?

**Comment by mallorypaine** [comment]
Should be present in releases 1.4 and 1.5 which are now available.
