### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by soffes** [path/FastImageCache#103]
The Carthage doesn't quite work.

    Project "FastImageCacheDemo.xcodeproj" has no shared schemes

Just need to the check the box to share the framework scheme. Thanks!

**Comment by mallorypaine** [comment]
cc @RuiAAPeres

**Comment by RuiAAPeres** [comment]
The scheme was shared in this commit: https://github.com/path/FastImageCache/commit/ea7650d78143015e57f32d4df0e9a9e927e9fbac

**Comment by RuiAAPeres** [comment]
So the issue, is that by default carthage will point to the latest release and not the latest commit. This fixes the issue @soffes:

```
github "path/FastImageCache" "8165e0a9bbf0f643805f609184a5341f966b6724"
```

**Comment by timonus** [comment]
I think this was technically done in https://github.com/path/FastImageCache/pull/99, but I can't seem to get the Carthage output to work. https://github.com/path/FastImageCache/pull/122 fixes it, once that's merged this could be closed.

**Comment by soffes** [comment]
@timonus for what it's worth, it works in my fork

**Comment by timonus** [comment]
:+1: nice
