### ISSUE TITLE
Question about byte alignment

### ISSUE THREAD

**Issue by luoyibu** [path/FastImageCache#110]
In your document, Core Animation can work with a image which has been made byte alignment directly without having to create a copy.
I found that by we can get a byte alignment image by setting the right bytesPerRow para of CGImageCreate function. 
My question is that should we call "CGImageCreate" every time when we load a image from disk?
Or after I get a byte alignment image in memory and save it to disk, the next time if I just call the function "initWithContentOfFile", can I get the byte alignment image?

**Comment by mallorypaine** [comment]
You're asking about implementation details of UIImage. Not sure what the answer is. Maybe ask on an Apple mailing list?
