### ISSUE TITLE
mmap return MAP_FAILED

### ISSUE THREAD

**Issue by felipeflorencio** [path/FastImageCache#114]
Hello guys i'm getting this issue running at iPad 2 using iOS 7, i using a huge collection view, and i always getting mmap return MAP_FAILED, does any one know how i fix this?       

 _bytes = mmap(NULL, _length, (PROT_READ|PROT_WRITE), (MAP_FILE|MAP_SHARED), fileDescriptor, _fileOffset);

        if (_bytes == MAP_FAILED) {
            NSLog(@"Failed to map chunk. errno=%d", errno);
            _bytes = NULL;
            self = nil;
        }

**Comment by mallorypaine** [comment]
Are you still experiencing this issue? Please re-open if so and we can discuss.
