### ISSUE TITLE
Feature Request to load image when no internet

### ISSUE THREAD

**Issue by vickyrappier** [path/FastImageCache#117]
Hello,

I am trying to use this component for the user profile settings picture that comes as URL in API and loads  to UI.

However my question is how this component can be used in case there is no internet and the image is actually cached and used.

Steps what I am requesting clarification for

1) Url Called for getting profile
2) URL responded with public url for the image to be viewed from.
3) FastImageCache  downloads the image and we show loader on the UIImageview while this task is done.
4) Image downloads and loads in screen.
5) Internet is switched off
6) Go to the user settings page again restarting the application

7) User should now see the image that is already cached in case the internet is offline
8) Incase the internet is online again is same URL then the cache image is used without getting again the image from the public image URL
9) In case the internet is online and the url is changed then the new image overwrites the older one keeping the updated copy.

So currently I am facing the No internet connection but already cached image not been displayed but blank. How to get hold of this.

Thanks.
Vicky

**Comment by mallorypaine** [comment]
This doesn't sound like it is related to Fast Image Cache since FIC doesn't download images. Your app is responsible for downloading, so the bug is probably there.
