### ISSUE TITLE
CocoaPods version bump

### ISSUE THREAD

**Issue by Emailrus** [path/FastImageCache#120]
1.4 has been around for almost 2 months, I guess it's safe to update podspec?

**Comment by domhof** [comment]
Any updates regarding this?

**Comment by raymondjavaxx** [comment]
+1

**Comment by mallorypaine** [comment]
Hey guys -- I have a new baby at home which means I'm failing to do anything meaningful with this project. Can any of you volunteer to update the podspec? It would be really helpful.

**Comment by domhof** [comment]
Sure, where can I find the original podspec?

**Comment by domhof** [comment]
Any news? :)

**Comment by domhof** [comment]
I have created a fork of this project and registered a pod in CocoaPods under the name "DHFastImageCache" (pod 'DHFastImageCache', '~> 1.4.0'). It includes the 1.4 source code. I will also try to integrate some of the pull requests. I hope this helps someone!

**Comment by mallorypaine** [comment]
Baby slept through the morning and I had some time to figure this out. Cocoapods now has access to releases 1.4 and 1.5.
