### ISSUE TITLE
25 FPS on iPad 3

### ISSUE THREAD

**Issue by Axlle** [path/FastImageCache#126]
I'm running the Demo App on an iPad 3 and getting 25 FPS when scrolling up and down (20 FPS without #125). The app becomes CPU-bound once each cell is changing every frame. An iPad 3 does not have the CPU to create 100+ `UIImage`s, assign them to `UIImageView`s and commit the changes to Core Animation.

<img width="1012" alt="screen shot 2016-02-04 at 5 18 59 pm" src="https://cloud.githubusercontent.com/assets/1561234/12835255/68e49bb0-cb63-11e5-804b-787b2f4b54ba.png">

A workaround I have on [this branch](https://github.com/Axlle/FastImageCache/commit/e23d5d4cde7342a906a69188d8dc01bce5717d25) is to wrap every image fetch in a `NSBlockOperation`. The operation guarantees that the app will get 60 FPS because it avoids returning all 100+ images in a single frame. This is most noticeable on an iPad 3, which can only perform ~7 image updates per frame.

I feel that the cache should provide async and cancellable requests, by default, so that every use of the cache does not need to implement its own throttling. Regardless of the speed of the device, and no matter how amazing the cache, there is always a limit on the number of images that can be fetched in a single frame because each request takes a non-zero amount of time.

Thoughts?

I am happy to work on this, given a bit of guidance on the internal threading and the callback structure of the image cache.

**Comment by mallorypaine** [comment]
I'll need to investigate what has happened to performance. On device, we should be achieving 60fps without issue.

**Comment by mallorypaine** [comment]
I don't have an iPad 3 at home, but I ran some tests on older iPhones and didn's see anything unusual. I do need to track down this device. What version of iOS is it running?

**Comment by Axlle** [comment]
It's running iOS 8.4.

The image cache isn't slow, UIKit is. I'm testing the performance on an iPad 3 because the iPad 3 historically has the worst graphics performance of any iOS device.

Replacing the table view cell's call to `retrieveImageForEntity:withFormatName:completionBlock:` with `asynchronouslyRetrieveImageForEntity:withFormatName:completionBlock:` solves the frame rate problem, but then it becomes possible to overload the cache.

```
2016-02-08 11:09:27.974 FastImageCacheDemo[196:18240] FICImageTable - unable to evict entry from table 'com.path.FastImageCacheDemo.FICDPhotoSquareImage32BitBGRAFormatName' to make room. New index 400, desired max 400
2016-02-08 11:09:28.137 FastImageCacheDemo[196:18240] FICImageTable - unable to evict entry from table 'com.path.FastImageCacheDemo.FICDPhotoSquareImage32BitBGRAFormatName' to make room. New index 401, desired max 400
2016-02-08 11:09:28.289 FastImageCacheDemo[196:18240] FICImageTable - unable to evict entry from table 'com.path.FastImageCacheDemo.FICDPhotoSquareImage32BitBGRAFormatName' to make room. New index 402, desired max 400
2016-02-08 11:09:28.442 FastImageCacheDemo[196:18240] FICImageTable - unable to evict entry from table 'com.path.FastImageCacheDemo.FICDPhotoSquareImage32BitBGRAFormatName' to make room. New index 403, desired max 400
...
```

Note: I did change the demo app to have 5000 _unique_ photos instead of 100, because 100 photos never exercised the cache's 400 image limit.

**Comment by Axlle** [comment]
@mallorypaine It looks like I am reproducing #82 with the demo app. The code I am running is [here](https://github.com/Axlle/FastImageCache/commits/async_fetch). Should the cache not have a overflow list for the extra images when there are more images requested than can fit in the cache?

**Comment by mallorypaine** [comment]
What are your exact steps to repro #82?

**Comment by Axlle** [comment]
I was scrolling down fast enough to get 400+ requests in-flight at the same time. I guess it depends on the device but it was easy with the iPad 3, which can only process a few images a second.

**Comment by mallorypaine** [comment]
I believe your PR addressed this.
