### ISSUE TITLE
UIImageView(Category)

### ISSUE THREAD

**Issue by alexnaldo** [path/FastImageCache#130]
Guys,

Make it simple for global usage. To use this library we need to create +100 lines. 

UIImageView(Category) can turn it very simple, like SDWebImage, AlamofireImage, etc.

**Comment by mallorypaine** [comment]
This is a specialized high-performance solution that only works with known sizes of images. I suppose if this project were completely rearchitected to eliminate image formats and also included its own networking layer, then this request would be feasible. I don't see this happening in the short term.
