### ISSUE TITLE
Lower FPS than conventional way!

### ISSUE THREAD

**Issue by santanu4ver** [path/FastImageCache#131]
I tested the supplied demo project within the library, so far I've tested this in iOS simulator (does this specifically needs physical device to test?) and have 'conventional' way always higher FPS than the library FPS. Conventional tab 50-51 FPS where library tab drops to 37 FPS.

**Comment by mythodeia** [comment]
use real device and test again

**Comment by santanu4ver** [comment]
Fantastic! So smoother than even my thoughts are :+1: Thanks for this lovely API, gonna use in my project.
