### ISSUE TITLE
Writable data is never removed from memory by the operating system ?

### ISSUE THREAD

**Issue by dongyu430** [path/FastImageCache#135]
question:

>> Writable data is never removed from memory by the operating system?
FastImageCahe Use of the model can be written,   memory warning how to release。

https://developer.apple.com/library/ios/documentation/Performance/Conceptual/ManagingMemory/Articles/AboutMemory.html
 
Although OS X supports a backing store, iOS does not. In iPhone applications, read-only data that is already on the disk (such as code pages) is simply removed from memory and reloaded from disk as needed. Writable data is never removed from memory by the operating system. Instead, if the amount of free memory drops below a certain threshold, the system asks the running applications to free up memory voluntarily to make room for new data. Applications that fail to free up enough memory are terminated.

**Comment by mallorypaine** [comment]
The memory is file-mapped and can be purged from the VM system as needed and also re-read from disk as necessary.

**Comment by victorstewart** [comment]
[https://stackoverflow.com/a/6273174/5689597](https://stackoverflow.com/a/6273174/5689597)

> [pages] are simply dropped (if they are clean) or are written to the underlying file and then dropped (if they are dirty).

**Comment by mallorypaine** [comment]
@victorstewart did you have a question?

**Comment by victorstewart** [comment]
@mallorypaine nope just had had the same question after reading the iOS virtual memory documentation about how the OS would only evict read-only pages.... then seeing the chunks were mapped with read+write.... and wondering if thus they would not be.

but then i stumbled upon the point i quoted above, and so put it here so someone else in the future with the same concern can find the clarity.
