### ISSUE TITLE
Property `UUID` duplicate(conflict) with other Library :(  

### ISSUE THREAD

**Issue by iShawnWang** [path/FastImageCache#137]
**Awesome Lib, i learn a lot from this project :) ~**

- I am using a Back-end Service [Leancloud](https://leancloud.cn) which likes [Firebase Storage](https://firebase.google.com/docs/storage/)
- Then i follow README to setup my model class named `User`, it has a property `@property (copy,nonatomic) NSString *avatarPath;` to storage the avatar path of user, i implement the `FICEntity` and there is no compile warning on Xcode .
- But when i run the app on the simulator , i got following crash on `main.m` :

```objective-c
2016-07-09 13:07:21.718 PiChat[2538:75333] [ERROR] -[AVObject(Subclass) setValue:forKey:] [Line 2273] Class User may contain a reserved property: UUID, see https://leancloud.cn/docs/ios_os_x_guide.html#AVObject for more infomation.
2016-07-09 13:07:21.794 PiChat[2538:75333] *** Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<User 0x7fba4240a240> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key UUID.'
```

- It looks like that `Leancloud` use  property `UUID` internal which cause conflict  with `FastImageCache` protocol `FICEntity` , the [document](https://leancloud.cn/docs/leanstorage_guide-ios.html#保存选项) of `Leancloud` announced `uuid` is reserved ,and my heart sinks ,cause `Leancloud` doesn't provide English Document :(

**So,what should do with this problem ?**
Currently ,my solution is to create a `child Entity` named `UserPhoto` which implement `FICEntity` protocol to replace the original property `@property (copy,nonatomic) NSString *avatarPath;`

**Any suggestion on this problem ?**
 And should `FastImageCache` rename property `UUID` in `FICEntity` with a unique name like `FIC_UUID` to avoid conflict with other library ,cause `UUID` is a very common name.

~

**Comment by iShawnWang** [comment]
### Update :
- All my model is subclass of `AVObject` which reserve property `uuid ` internal
- So create a child entity named `UserPhoto` which subclass `AVObject` to contain `@property (copy,nonatomic) NSString *avatarPath;` will not work.
- May be the only way is to fork and modify the source code , but it takes extra effort to maintain the code when `FastImageCache` official repo update :(

**Comment by mallorypaine** [comment]
Would definitely appreciate a PR that fixes this issue. With a small baby at home, I rarely have time to work on fixes myself anymore, but if you write a PR, I'll work with you to get it merged.

**Comment by iShawnWang** [comment]
**Yeah, it is really more important to be a good father.**  

- I just create a new pull request :

1. I add prefix `FIC` for all the property and method in `FICEntity` protocol
2. I update `FICImageCache.m` with little change above
3. I update `FICDPhoto` which confirms to protocol `FICEntity` in FastImageCacheDemo
4. The new code works great in `FastImageCacheDemo` and my App.

**The problem is if this PR is merged to `master` ,all the developers using this lib may take some unnecessary time to modify their classes which confirm to `FICEntity`.**

Hoping i am doing this the right way. 😊

**Comment by mallorypaine** [comment]
I merged your PR.
