### ISSUE TITLE
Why are images blown up to the same scale as the screen?

### ISSUE THREAD

**Issue by rojo69** [path/FastImageCache#144]
The backing file becomes four times larger on retina devices.

**Comment by mallorypaine** [comment]
Yes, that is correct. 4x the pixels = 4x the storage. I hope you aren't aiming to show blurry 1x content on 2x screens, but if that's your goal you can certainly achieve it by using one image format on 1x screens and a 2nd smaller image format on 2x screens.

**Comment by rojo69** [comment]
So if the UIImages I would like to store have the size 200 * 400 and scale 1.0 I should configure FIC on retina devices to store images of size 100 * 200?
