### ISSUE TITLE
CGContextClearRect() intermittent crash inside of drawingBlockForImage:withFormatName:

### ISSUE THREAD

**Issue by jaredsinclair** [path/FastImageCache#31]
One of my beta testers is getting a recurring crash inside of drawingBlockForImage:withFormatName:, specifically when CGContextClearRect() is called.

The crashed thread is: 
com.path.FastImageCacheQueue.

The error given is:
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x1096d0000

The call stack is 7 or 8 frames deep inside the implementation of CGContextClearRect() when it crashes.

My drawing code is copied directly from the recommended sample code in the documentation, which includes the call to clear the passed-in context before performing the rest of the drawing code.

Attached below is a screenshot of the crashed thread:

![screen shot 2014-01-06 at 6 47 37 pm](https://f.cloud.github.com/assets/720600/1855372/2b56b968-772d-11e3-87c9-ae714c860012.png)

This is on an iPhone 5s running iOS 7.1.

**Comment by aaronwasserman** [comment]
@mallorypaine @LucasTizma hey guys -- just stumbled upon this thread as we're experiencing this crash in our latest version of Periscope iOS.  We're using the latest cocoapod for FIC.  Have you seen any other reports of this crash still occurring?  I assume the latest cocoapod includes the fix from back in March?

Thanks so much for your help.
