### ISSUE TITLE
Failed to map chunk. errno=22

### ISSUE THREAD

**Issue by mt19** [path/FastImageCache#69]
Hi,
I'd like to report some information about this error and ask about the reasons and possible ways to fix it.

One of users ran into an issue when my app doesn't show a downloaded image. The image was downloaded successfully but it was not added to FIC. 

I found "Failed to map chunk. errno=22" and "ERROR: FastImageCache error occured with message: *** FIC Error: -[FICImageTable _chunkAtIndex:] failed to get chunk for index 5" log messages.

After a search in the sources (v1.3) I found mmap call that led to "Failed to map chunk. errno=22" message.
errno 22 - EINVAL. Something wrong with input parameters: probably, length or offset.

Thanks!

**Comment by mallorypaine** [comment]
Not enough info here to investigate further.
