### ISSUE TITLE
importing a batch of photos causes large memory allocation then killed by system

### ISSUE THREAD

**Issue by jerrium** [path/FastImageCache#76]
Thanks for great fast image cache first.
I have done a load test of importing a batch of photos about 1000+ from system album. The app crashed when the process went about 50%. 
Viewing the crash log, I found the some info like this:
 My App <ab092f688257317aabe8cb11e3f15077>         7.253      166401                0           -         41854   50  [per-process-limit]  (frontmost) (resume)

166401* 4=665M(loaded momery)

and I have launtched the profile, capturing a screenshot like this:
![image](https://cloud.githubusercontent.com/assets/2020472/4976779/867460f0-6923-11e4-95a5-11e0bafddb0d.png)
 it seems that mmap causes the huge memory allocation then app is killed by system.
At the same time, I did not call retrieve image function to show image.
Is there a way to write a batch of photos(about 1000-5000) to image table without huge memory allocation?
My test environment: iphone6, ios8.1, xcode6.1, arm64
Thanks a lot.

**Comment by cleexiang** [comment]
@jerrium do you have any idea? I have the same problem

**Comment by Sega-Zero** [comment]
Faced the very same trouble and solved it by patching `saveMetadata` method like this:

```objectivec
- (void)saveMetadata {
    @autoreleasepool {
        [_lock lock];
        
        NSDictionary *metadataDictionary = [NSDictionary dictionaryWithObjectsAndKeys:
                                            [_indexMap copy], FICImageTableIndexMapKey,
                                            [_sourceImageMap copy], FICImageTableContextMapKey,
                                            [[_MRUEntries array] copy], FICImageTableMRUArrayKey,
                                            [_imageFormatDictionary copy], FICImageTableFormatKey, nil];

        __block int32_t metadataVersion = OSAtomicIncrement32(&_metadataVersion);

        [_lock unlock];
        
        static dispatch_queue_t __metadataQueue = nil;
        static dispatch_once_t onceToken;
        dispatch_once(&onceToken, ^{
            __metadataQueue = dispatch_queue_create("com.path.FastImageCache.ImageTableMetadataQueue", NULL);
        });
        
        dispatch_async(__metadataQueue, ^{
            // Cancel serialization if a new metadata version is queued to be saved
            if (metadataVersion != _metadataVersion) {
                return;
            }

            @autoreleasepool {
                NSData *data = [NSJSONSerialization dataWithJSONObject:metadataDictionary options:kNilOptions error:NULL];

                // Cancel disk writing if a new metadata version is queued to be saved
                if (metadataVersion != _metadataVersion) {
                    return;
                }

                BOOL fileWriteResult = [data writeToFile:[self metadataFilePath] atomically:NO];
                if (fileWriteResult == NO) {
                    NSString *message = [NSString stringWithFormat:@"*** FIC Error: %s couldn't write metadata for format %@", __PRETTY_FUNCTION__, [_imageFormat name]];
                    [self.imageCache _logMessage:message];
                }
            }
        });
    }
}
```

The upper `@autoreleasepool` is for `metadataDictionary`, the inner `@autoreleasepool`for NSData object. When we have a very intense cache saving, the `saveMetadata` call avalanche leads to huge amount of `metadataDictionary` objects, that are naturally occupies the whole release pool. The situation becomes worse, when each entry of the dictionary contains thousands of entries (in case `FICImageFormat.maximumCount` set to 1000 for example). With this fix my project's memory consumption falls down dramatically.

@mallorypaine, should I create a PR for this?

**Comment by Sega-Zero** [comment]
Also, it would be nice if `@autoreleasepool` will be added to `_retrieveImageForEntity:withFormatName:loadSynchronously:completionBlock:`, wrapping `if (needsToFetch) {` body too. In that case anything that is created during entity's  `imageForFormat` call will be released asap.

**Comment by mallorypaine** [comment]
@Sega-Zero yes, a PR would be great. Thanks!
