### ISSUE TITLE
App crashing due to memory pressure

### ISSUE THREAD

**Issue by naveenkumar-sourcebits** [path/FastImageCache#79]
Hi,

When I use the Fast image cache for loading images in a table view, after scrolling for some time the app crashes dud to memory pressure. I thought the main culprit might be my model object (core data) which might be taking too much memory  when called from tableview's cell API.

[FICImageCache sharedImageCache] asynchronouslyRetrieveImageForEntity:imageEntity withFormatName:ImageAvatarFormatFriendsList completionBlock:^(id<FICEntity> entity, NSString *formatName, UIImage *image)

and I created a small model object called ImageEntity which contains necessary attributes like object ID and image path to respect the FICEntity protocol. 

Even though having this small model objects app crashes when I do scrolling in the table view.

Here are the some more points to analyse this issue.

1. Table view is going to load friends list.
2. Tableview's cell API is responsible to fetch the image and set to cell's avatar image view.

Any idea why it is taking too much memory?

Any help is highly appreciated.

Thanks.

**Comment by mallorypaine** [comment]
Pretty sure any memory pressure is being caused either by the way you are decoding and drawing images or by a leak in your app code. Either way, it's unlikely that FIC is the culprit. If you provide an instruments trace, I could take a look. Closing until there's actionable info...

**Comment by naveenkumar-sourcebits** [comment]
Currently, I am not working on that, if possible, I can check and give you more info. Thanks for the reply.
