### ISSUE TITLE
FICImageFormat pixelSize not imageSize/scale

### ISSUE THREAD

**Issue by kganser** [path/FastImageCache#90]
FICImageFormat pixelSize is currently imageSize multiplied by the UIScreen scale (2.0 for retina).  It seems like it should be divided by 2.0 instead.

**Comment by mallorypaine** [comment]
Why do you think this? What problems are you seeing?

**Comment by kganser** [comment]
I just wanted to verify that the UIImage returned by a web service is the size required by the format.  If I set up the image format with the image's intrinsic dimensions (imageSize), and the UIImage I get back should be scaled to these dimensions / 2, then it seems like the more useful value to expose is the reverse-scaled imageSize / 2 to confirm that it matches UIImage.size.  Correct me if I'm wrong.

Thanks for the library!

**Comment by mallorypaine** [comment]
FICImageFormat has two properties: imageSize and pixelSize. imageSize is the size of the image as reported by UIImage and does take into account screen scale. pixelSize is the size of an image in actual pixels of data regardless of screen scale. So a UIImage of size (50, 50) at scale 2 would use a format with imageSize of 50x50 and pixelSize of 100x100.
