### ISSUE TITLE
[UIApplication sharedApplication] is not available for iOS 8 Extensions

### ISSUE THREAD

**Issue by Sega-Zero** [path/FastImageCache#91]
The code
```objectivec
[[UIApplication sharedApplication] isProtectedDataAvailable]
```
cannot be compiled for any type of extensions due to unavailability of UIApplication. There should be another approach of detecting locked screen, for example as suggested here: http://stackoverflow.com/a/27934173/1254172

**Comment by mallorypaine** [comment]
Please feel free to submit a pull request.

**Comment by Sega-Zero** [comment]
I'm not sure i won't break something since i haven't understood this feature yet =) As a workaround to be able to compile this code, i wrapped this block of code with a define
