### ISSUE TITLE
Why Conventional Mode run more smoothly than Fast Image Cache Mode on Simulator iOS8?

### ISSUE THREAD

**Issue by shenruisi** [path/FastImageCache#95]
Conventional Mode runs above 55 FPS

**Comment by mallorypaine** [comment]
Fast Image Cache is optimized for the device, not the simulator. Simulator performance is irrelevant.

**Comment by shenruisi** [comment]
Thanks i understand ,but  I have just tested, even on the device, iPad simulator runs great, nearly 60fps, but why it is not good on iPhone simulator.

**Comment by mallorypaine** [comment]
I don't know. Simulator performance is not important to this project so I don't plan on spending time to find out.

**Comment by shenruisi** [comment]
OK. Sorry about that.  Thanks very mush.

**Comment by mythodeia** [comment]
@shenruisi  when using the simulator you are actually using the ram of your mac/imac which is way more than the ram you have available in your device. Thats why its so smooth.
it does not provide credible info as to how the app would perform on an actual device. 
You should run on device for proper results and comparison

**Comment by Jercik** [comment]
@shenruisi This is something I also encountered while working on another project. Simulator for some reason just can't keep even 60 FPS. I measured time intervals between frames, and on simulator they fluctuate even if UI is not very complicated. FPS should be measured on device.
