### ISSUE TITLE
Is there a way to show progress?

### ISSUE THREAD

**Issue by iceNuts** [path/FastImageCache#97]
Hi there,

I see example about loading an image, but as we may need to download image online. It's better to have a way to show loading progress. I am wondering what is the best way?

Thanks.

**Comment by mallorypaine** [comment]
FIC asks your app to download the image and then tell FIC via a completion block when that image has been downloaded. In your code, while you download the image, you can show progress. FIC has no knowledge of how you are transferring images or how those transfers are progressing.
